### ISSUE TITLE
Decide on Tech

### ISSUE THREAD

**Issue by N0matic** [cml2377/Coronacation#10]
- Auth-0
- Material UI
- SASS
- MongoDB
- Figma.com for frontend planning
- Tru.ly age verification
- Grocery api?

**Comment by anthonyagarza** [comment]
i suggest MERN since ya'll are familiar with that.

**Comment by N0matic** [comment]
So far we've got what, MERN, either SAS or Tailwind for the Frontend, I'm guessing Mongo for the backend, Auth0 for sign-ins....
